services:
  app:
    build: .docker/app
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_CONTAINER_EXTERNAL_PORT:-8080}:8085"
    networks:
      local:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo
      - opensearch
  mongo:
    build: .docker/mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    networks:
      local:
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_APP_USER: ${MONGODB_USER}
      MONGO_APP_PASSWORD: ${MONGODB_PASSWORD}
  opensearch:
    image: opensearchproject/opensearch:latest
    networks:
      local:
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - opensearch:/usr/share/opensearch/data
volumes:
  mongo:
  opensearch:
networks:
  local:
